name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Setup Java JDK
      uses: actions/setup-java@v2.0.0
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    
